### ISSUE TITLE
Send context on callbacks - protect from side effects

### ISSUE THREAD

**Issue by carlos-verdes** [eram/ts-fsm#4]
The transition callbacks should receive and instance of the fsm event handler and the state from/to:
```js
function onOpen(eh: EventHandler, from: State, to: State): Promise<void> {

    console.log("onOpen...");
    return eh.dispatch(Events.openComplete);
}
```

With your current code I would not be able to execute 2 instances of the same FSM, which is a problem if for example you want to use an FSM per user (to handle his user state).

**Comment by eram** [comment]
the trick is to bind the callbacks to the object. see how callbacks are bound in src\__test__\stateMachine.test.ts

**Comment by eram** [comment]
the trick is to bind the callbacks to the object. see how callbacks are bound in src\__test__\stateMachine.test.ts
